/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  safelist: [
    'max-w-6xl',
    'mx-auto',
    'px-6',
    'py-10',
    'bg-white',
    'rounded-2xl',
    'shadow-sm',
    'border',
    'border-gray-100',
    'transition-all',
    'duration-300',
    'hover:shadow-md',
    'hover:-translate-y-[2px]',
    'pb-3',
    'text-gray-500',
    'transition',
    'border-b-2',
    'border-black',
    'text-black',
    'font-medium',
    'px-3',
    'py-1',
    'rounded-full',
    'text-sm',
    'font-medium',
    'bg-purple-50',
    'bg-rose-50',
    'bg-blue-50',
    'bg-emerald-50',
    'bg-gray-50',
    'border-purple-200',
    'border-rose-200',
    'border-blue-200',
    'border-emerald-200',
    'border-gray-200',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}